export interface Product {
}
// Generated by https://quicktype.io

export interface Product {
    id:          number;
    name:        string;
    description: string;
    price:       number;
    imageUrl:    string;
}
